### ISSUE TITLE
请求加入推送通知

### ISSUE THREAD

**Issue by Mr54233** [HCLonely/AWA-Helper#10]
server酱
pushplus
tgbot
都可以 , 因为我这主要是挂在青龙上运行 , 出了问题看不到 , 希望能加入推送通知 , 哪怕是出了问题再推送也可以

**Comment by HCLonely** [comment]
已实装https://github.com/HCLonely/AWA-Helper#%E6%8E%A8%E9%80%81%E9%85%8D%E7%BD%AE%E5%8F%AF%E9%80%89
