### ISSUE TITLE
最新2.2.5版本报错

### ISSUE THREAD

**Issue by inory121** [HCLonely/AWA-Helper#22]
如图
![QQ截图20230402125456](https://user-images.githubusercontent.com/35392664/229332155-ddcd4924-62b6-415f-bf4f-8dbf72279a75.png)

**Comment by inory121** [comment]
好像还是不行
![image](https://user-images.githubusercontent.com/35392664/229348512-6877778a-2c16-4702-8e62-ee0cb5e150ef.png)

**Comment by HCLonely** [comment]
再更新一下试试有没有解决

**Comment by inory121** [comment]
好了，谢谢
