### ISSUE TITLE
需要新型任务支持

### ISSUE THREAD

**Issue by Mr54233** [HCLonely/AWA-Helper#3]
【全區】每日任務：Fresh siding!任務內容：更換邊框。
前往任務：http://www.alienwarearena.com/account/personalization#borders
任務獎勵：5 ARP
比如这个换边框的任务

![image](https://user-images.githubusercontent.com/46802509/169434809-6bae6345-9138-4cff-a6eb-473591b391b8.png)
![image](https://user-images.githubusercontent.com/46802509/169434828-e68c2156-6707-4e8a-8bf8-3641d92104ef.png)
还有这个外星人入侵，随便丢两个上去提交就行

**Comment by HCLonely** [comment]
换边框的任务本来就支持，外星人入侵是美区任务，有人机验证的，目前无法支持
