### ISSUE TITLE
由不明原因计算死循环导致服务器死机

### ISSUE THREAD

**Issue by Cliencer** [HCLonely/AWA-Helper#48]
![IMG_0705](https://github.com/HCLonely/AWA-Helper/assets/79413453/8b4963f9-f86b-420c-9dd8-17153b21b09a)
由于多次服务器宕机，我保存了宕机时的截图，发现是awa-helper导致的问题，请作者帮忙排查下原因

**Comment by Cliencer** [comment]
检查了宕机时间和awahelper的日志，发现是在检查任务连接不上时报错，后续占用资源大幅增加，服务器宕机。
最近一次宕机发生在更新新版时，似乎正在解压文件。
服务器系统ubuntu20.04，用root账户运行

**Comment by HCLonely** [comment]
helper和manager的日志发一下

**Comment by Cliencer** [comment]
> helper和manager的日志发一下

[
[logs.zip](https://github.com/HCLonely/AWA-Helper/files/14994443/logs.zip)
](url)
其中时间间隔较大的就是宕机了。。。

**Comment by HCLonely** [comment]
应该是Steam任务一直没完成导致运行时间太长了，设置一下超时，建议设置4~6小时
```
timeout: 0 # 超时设置，单位：秒，0为不限制。如果程序运行超过此时间后还在运行，则终止此程序。
```
